development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Noteable
  admin_email: jacob@blowout.dk
  
test:
  <<: *non_production_settings
  
production:
  site_url: http://noteablehq.com
  site_name: Noteable
  admin_email: jacob@blowout.dk
